# Generated by Django 3.0.7 on 2020-06-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200619_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='solicitante',
            new_name='email',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
