# Generated by Django 3.0.7 on 2020-06-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200619_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
