# Generated by Django 3.0.7 on 2020-06-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
